services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "3000:3000"
      - "5000:5000"
      - "2376:2376"
    restart: always

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-blueocean
    networks:
      jenkins:
        aliases:
          - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ${HOME}:/home
    ports:
      - "49000:8080"
      - "50000:50000"
    depends_on:
      - jenkins-docker
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: jenkins-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - jenkins
    ports:
      - "9000:9000"
    depends_on:
      - jenkins
    restart: always

networks:
  jenkins:
    name: jenkins
    external: true

volumes:
  jenkins-docker-certs:
  jenkins-data: