global:
  scrape_interval: 10s     # Changed from 15s to 10s as per requirement
  evaluation_interval: 10s # Changed to match scrape_interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'jenkins'
    metrics_path: '/prom'  # Changed from /prometheus to /prom as per requirement
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']